<a href="https://colab.research.google.com/github/elyorbek8/ML_journey/blob/main/ml_steps3_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Encoding: tranforming characterical values to a numeric form

# Ordinal Encoding

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [22]:
df = pd.read_csv('https://raw.githubusercontent.com/elyorbek8/ML_journey/refs/heads/main/housing.csv')
df.head(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   
5    -122.25     37.85                52.0        919.0           213.0   
6    -122.25     37.84                52.0       2535.0           489.0   
7    -122.25     37.84                52.0       3104.0           687.0   
8    -122.26     37.84                42.0       2555.0           665.0   
9    -122.25     37.84                52.0       3549.0           707.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  
5       413.0       193.0         4.0368            269700.0        NEAR BAY  
6      1094.0       514.0         3.6591            299200.0        NEAR BAY  
7      1157.0       647.0         3.1200            241400.0        NEAR BAY  
8      1206.0       595.0         2.0804            226700.0        NEAR BAY  
9      1551.0       714.0         3.6912            261100.0        NEAR BAY

In [3]:
ocean_prox = df['ocean_proximity']
ocean_prox.head()

0    NEAR BAY
1    NEAR BAY
2    NEAR BAY
3    NEAR BAY
4    NEAR BAY
Name: ocean_proximity, dtype: object

In [5]:
ocean_prox.value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [6]:
ocean_prox.info()

<class 'pandas.core.series.Series'>
RangeIndex: 20640 entries, 0 to 20639
Series name: ocean_proximity
Non-Null Count  Dtype 
--------------  ----- 
20640 non-null  object
dtypes: object(1)
memory usage: 161.4+ KB


In [30]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()

ocean_prox_encoded = ordinal_encoder.fit_transform(ocean_prox.values.reshape(-1, 1))
ocean_prox_encoded

array([[3.],
       [3.],
       [3.],
       ...,
       [1.],
       [1.],
       [1.]])

In [38]:
ocean_prox_encoded[[6244, 5634, 19813, 7299, 6648, 16329, 11600, 5673, 6787, 10052]]

array([[0.],
       [4.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [4.],
       [0.],
       [1.]])

In [35]:
ocean_prox.sample(10).index

Index([6244, 5634, 19813, 7299, 6648, 16329, 11600, 5673, 6787, 10052], dtype='int64')

In [39]:
ocean_prox.iloc[[6244, 5634, 19813, 7299, 6648, 16329, 11600, 5673, 6787, 10052]]

6244      <1H OCEAN
5634     NEAR OCEAN
19813        INLAND
7299      <1H OCEAN
6648      <1H OCEAN
16329        INLAND
11600     <1H OCEAN
5673     NEAR OCEAN
6787      <1H OCEAN
10052        INLAND
Name: ocean_proximity, dtype: object

# One hot encoding: ```sklearn OneHotEncoder```

In [50]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()

In [51]:
ocean_prox_1hot = one_hot_encoder.fit_transform(ocean_prox.values.reshape(-1, 1))
ocean_prox_1hot.toarray()

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

# One hot encoding: ```pandas get_dummies()```

In [44]:
ocean_prox_dummies = pd.get_dummies(ocean_prox)
ocean_prox_dummies.head()

<1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
0      False   False   False      True       False
1      False   False   False      True       False
2      False   False   False      True       False
3      False   False   False      True       False
4      False   False   False      True       False

In [45]:
type(ocean_prox_1hot)

scipy.sparse._csr.csr_matrix